name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          # Issue ref: https://github.com/actions/setup-python/issues/401
      - name: Install pre-commit hooks
        run: |
          pip install pre-commit
          pre-commit install
      - name: Lint code
        run: pre-commit run --all-files
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
