name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - name: Install pre-commit hooks
        run: |
          pip install pre-commit
          pre-commit install
      - name: Lint code
        run: pre-commit run --all-files
